name : Workflow (Lint, Security, Test, Env)

on :
	push : 
		branches: [main]
	pull_request:
		branches : [main]
	workflow_dispatch:
jobs :
	run-bash-script:
		runs-on: ubuntu-latest

		steps:
			- name : Checkout Repository
			uses : actions/checkout@v3

			- name : Run Script .sh
			env:
				VAR : "Hello From Github Actions"
			run : bash scripts/script.sh

